version: '3'
services:
  supasec-db:
    container_name: 'supasec-db'
    image: 'postgres:alpine'
    restart: unless-stopped
    volumes:
      - supasec-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=supasec
      - POSTGRES_USER=supasec
      - POSTGRES_PASSWORD=supasec

  init-prisma:
    container_name: 'prisma'
    image: 'node:alpine'
    depends_on:
      - supasec-db
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - DATABASE_URL=postgresql://supasec:supasec@supasec-db:5432/supasec?schema=private
    command: npx prisma db push --accept-data-loss --force-reset

  dev-supasec-bot:
    container_name: 'dev-supasec-bot'
    depends_on:
      - supasec-db
      - init-prisma
    image: 'node:alpine'
    volumes:
      - ./:/app
    working_dir: /app
    env_file: .env
    command: sh -c "npm install && npm run dev"
    environment:
      - DATABASE_URL=postgresql://supasec:supasec@supasec-db:5432/supasec?schema=private
      - VT_API_BASE_URL=http://virustotal:3000/api/
    networks:
      - docker_shared_network
      - default

  # sudo docker exec -it dev-supasec-bot sh

networks:
  docker_shared_network:
    external: true

volumes:
  supasec-db:
