version: '3'
services:
  supasec-bot:
    container_name: 'supasec-bot'
    image: 'shahradel/supasec:dev'
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
    env_file: .env.production.local
    networks:
      - docker_shared_network

networks:
  docker_shared_network:
    external: true
