version: '3'
services:
  supasec-bot:
    container_name: 'supasec-bot'
    image: 'node:alpine'
    volumes:
      - ./:/app
    working_dir: /app
    env_file: .env.production.local
    command: sh -c "npm install && npm run dev"